server:
  port: 8086
spring:
  application:
    name: provider
    #配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_car
    username: root
    password: "0903"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka

#配置mybatis
mybatis:
  mapper-locations=: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl